# Generated by Django 5.2.5 on 2025-11-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('original_file', models.FileField(upload_to='songs/originals/')),
                ('accompaniment_file', models.FileField(blank=True, null=True, upload_to='songs/accompaniments/')),
                ('is_instrumental', models.BooleanField(default=False, help_text='Tick if uploaded file is already instrumental (karaoke).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
