# Generated by Django 5.2.5 on 2025-12-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedsong',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedsong',
            name='lyrics_image',
            field=models.ImageField(blank=True, null=True, upload_to='songs/lyrics_images/'),
        ),
    ]
